package test.oob.exception;

public class ExceptionThrowDemo2 {

	public static void fangfa1() {

		System.out.println();
	}

}
